
/*创建数据库 XSGL */

CREATE DATABASE XSGL
ON
(	NAME = XSGL_Data,
	FILENAME = 'F:\课程\数据库\SQL SEVER DB\XSGL\XSGL.mdf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 5%)
LOG ON(
	NAME = XSGL,
	FILENAME = 'F:\课程\数据库\SQL SEVER DB\XSGL\XSGL_Log.ldf',
	SIZE = 2MB,
	MAXSIZE = 5MB,
	FILEGROWTH = 1MB
);


/*学院信息表*/
CREATE TABLE DEPT
(	DNO CHAR(4) NOT NULL,
	DNAME CHAR(30) NOT NULL,
	DEAN CHAR(10),
	PRIMARY KEY(DNO)
);

/*学生信息表*/
CREATE TABLE STUDENT
(
	SNO CHAR(8) NOT NULL UNIQUE,
	SANME CHAR(10) NOT NULL,
	AFE SMALLINT,
	SEX CHAR(2),CHECK(SEX IN('男','女')),
	DNO CHAR(4) NOT NULL,
	BIRTHDAY DATETIME,
	PRIMARY KEY (SNO),
	FOREIGN KEY(DNO) REFERENCES dept
);

/* 课程信息表 课程信息表 */
CREATE TABLE COURSE
(	CNO CHAR(8) NOT NULL UNIQUE,
	CNAME CHAR(30) NOT NULL,
	TNAME CHAR(10),
	CREDIT FLOAT,
	ROOM CHAR(30),
	PRIMARY KEY (CNO)
);

/*学生选课表*/
CREATE TABLE SC
(	SNO CHAR(8) NOT NULL,
	CNO CHAR(8) NOT NULL,
	GRADE FLOAT,
	CHECK (GRADE BETWEEN 0 AND 100),
	PRIMARY KEY (SNO,CNO),
	FOREIGN KEY (SNO) REFERENCES  STUDENT,
	FOREIGN KEY (CNO) REFERENCES COURSE

);


